table test_아마존
	lineageTag: 593c8634-73de-4a76-ac5e-baa66aaa7379

	measure avgPrice = AVERAGE('test_아마존'[Close])
		lineageTag: c985b634-4b73-4b23-83af-e981321ffe18

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6c40eaec-e89d-4036-a0b5-44bd71bab9d9
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 85f11082-8161-4d4d-b8f2-7b0321b47364
			defaultHierarchy: LocalDateTable_4d497cc5-063a-426a-91f5-2b74d5780a8b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Open
		dataType: double
		lineageTag: 12a812e3-2c37-47af-b957-f5b3ef16df92
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: 8ba1c1f8-2d47-4ad3-a233-e0b2259bade7
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: 399bf271-bc9f-4c50-9bc6-98d6d6f79bfd
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: e3176633-aaf3-4ae7-b59b-a85f8014e588
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Adj Close'
		dataType: double
		lineageTag: e3c0148c-723a-4462-bd04-81942354642b
		summarizeBy: sum
		sourceColumn: Adj Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: e0eb47e8-c0e4-474c-8635-2a0f445463fc
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition test_아마존 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\havef\OneDrive - onionbi.co.kr\_ONIONBI\07 Git_Repository\pbi2\AMZN_data_1999_2022.csv"),[Delimiter=",", Columns=7, Encoding=949, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Adj Close", type number}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

